### ISSUE TITLE
Gen2 Config error

### ISSUE THREAD

**Issue by mbox1** [jiristepan/hass-gen2-wallbox#4]
Adding new integration - Gen2 Config cause error: 

Logger: custom_components.gen2_wallbox.config_flow
Zdroj: custom_components/gen2_wallbox/config_flow.py:79
integrace: GEN2 Wallbox (dokumentace)
První výskyt: 00:22:51 (1 výskyty)
Naposledy logováno: 00:22:51

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core.py", line 1146, in _send_receive
    break
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 158, in raise_for_blocking_call
    raise RuntimeError(
RuntimeError: Caught blocking call to sleep with args (0.01,) inside the event loop by custom integration 'gen2_wallbox' at custom_components/gen2_wallbox/gen2wallbox.py, line 60: data = self.device.status(). (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 1146: break), please report it to the author of the 'gen2_wallbox' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/gen2_wallbox/config_flow.py", line 79, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gen2_wallbox/config_flow.py", line 42, in validate_input
    wallbox = GEN2_Wallbox(data["deviceid"], data["ip"], data["localkey"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gen2_wallbox/gen2wallbox.py", line 51, in __init__
    self.update()
  File "/config/custom_components/gen2_wallbox/gen2wallbox.py", line 60, in update
    data = self.device.status()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core.py", line 1554, in status
    result[k] = dict1[k]
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core.py", line 1226, in _send_receive
    self.dev_type,
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 158, in raise_for_blocking_call
    raise RuntimeError(
RuntimeError: Caught blocking call to sleep with args (0.1,) inside the event loop by custom integration 'gen2_wallbox' at custom_components/gen2_wallbox/gen2wallbox.py, line 60: data = self.device.status(). (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 1226: self.dev_type,), please report it to the author of the 'gen2_wallbox' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep

**Comment by jiristepan** [comment]
Should be fixed in version 0.5.0. All blocking calls are now async using asyncio

**Comment by mbox1** [comment]
Fixed, works. 
Thanks
